name: Deploy Workflow

 

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select an environment'
        required: true
        default: 'development'
        options:
         - a
         - b
         - c
         - development
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Print selected environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}"

 

      # Here you can add your deployment steps, conditionally run them based on the selected environment if necessary.
